import React from 'react';

import Logo from '../../../assets/logo-primary.png';

const PrivacyPolicyScreen = () => {
  return (
    <div className="max-w-3xl mx-auto p-6 text-gray-800 h-screen pt-20">
      {/*  Header */}
      <header className="fixed top-0 left-0 w-full bg-white shadow-md py-3 px-6 flex items-center justify-between z-50">
        {/* Logo on the Left */}
        <a href="https://xcellify.com/">
          <img src={Logo} alt="XcellifyLogo" className="h-14 w-auto" />
        </a>

        {/* Centered Content */}
        <div className="absolute left-1/2 transform -translate-x-1/2 text-center">
          <h1 className="text-xl font-semibold">Privacy Policy</h1>
          <p className="text-sm text-gray-500">Last Updated: 02/02/2025</p>
        </div>
      </header>

      <div className="mt-6 space-y-6 text-justify">
        {' '}
        <p className="font-bold">
          THIS PRIVACY POLICY (“POLICY”) DOCUMENT IS AN ELECTRONIC RECORD IN
          TERMS OF THE INFORMATION TECHNOLOGY ACT, 2000 AND RULES MADE
          THEREUNDER. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM
          AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
        </p>
        <p className="font-bold">
          THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF
          INFORMATION TECHNOLOGY ACT, 2000 AND RULES MADE THEREUNDER AND
          CONSUMER PROTECTION (E-COMMERCE) RULES, 2020, THE DIGITAL PERSONAL
          DATA PROTECTION ACT, 2023, THAT REQUIRES PUBLISHING THE RULES AND
          REGULATIONS, PRIVACY POLICY AND TERMS OF USE FOR ACCESS OR USAGE OF
          THIS PLATFORM.
        </p>
        <p>We are happy to have you here at Xcellify!</p>
        <p>
          This Privacy Policy (“<span className="font-bold">Policy</span>”)
          applies to the use of the website{' '}
          <a
            href="https://xcellify.com"
            className="underline text-blue-600 hover:text-blue-800"
          >
            https://xcellify.com{' '}
          </a>
          , any sub-domains, or any other medium authorized by the Company
          (hereinafter referred to as the “
          <span className="font-bold">Platform</span>”), owned by Xcellify
          Private Ltd, a company incorporated under the laws of India
          (hereinafter referred to as the “
          <span className="font-bold">Company</span>” “
          <span className="font-bold">Xcellify</span>” “
          <span className="font-bold">we</span>” “
          <span className="font-bold">us</span>” and “
          <span className="font-bold">our</span>”).
        </p>
        <p>
          The Platform serves as a one-stop marketplace for day-to-day needs of
          the students (“<span className="font-bold">Students</span>”) and their
          parents/legal guardians (“<span className="font-bold">Parents</span>
          ”), which is provided by third-party vendors/partners/sellers offering
          such products, goods and services listed on the Platform (“
          <span className="font-bold">Partner</span>”) and all of them shall
          collectively be referred to as the “
          <span className="font-bold">User(s)</span>”
        </p>
        <p>
          The Company is committed to respecting your online privacy and
          recognizes your need for appropriate protection and management of any
          information you share with the Company on and through the Platform.
        </p>
        <p>
          When you visit, use our Platform, or engage with any of our services,
          we recognize the trust you place in Us by sharing your information. We
          are committed to safeguarding your privacy and take this
          responsibility seriously. This Policy explains how the Company will
          collect, use, share and process your information in relation to use of
          the Platform.
        </p>
        <p>
          This Policy is being framed in view of the Information Technology Act,
          2000 read with Regulation 4 of the Information Technology (Reasonable
          Security Practices and Procedures and Sensitive Personal Data or
          Information) Rules, 2011 and Regulation 3(1) of the Information
          Technology (Intermediaries Guidelines and Digital Media Ethics Code)
          Rules, 2021 and the Digital Personal Data Protection Act, 2023.
        </p>
        <p>
          By accessing, browsing or otherwise using the Platform and/or by
          giving the Company your information and/or by explicitly giving your
          consent (as indicated and recorded on the Platform), you expressly
          agree to be bound by the terms of this Policy. If you do not agree
          with the terms mentioned herein, you may exit this Platform and
          restrict your access. By accepting this Policy, you understand and
          agree to the collection, use, sharing and processing of personal
          information as described herein. If you provide the Company with
          personal information about someone else, including your child, ward,
          family members, company, colleagues etc. you confirm that (a) such
          information is accurate and up-to-date; (b) such person is aware that
          you have provided their information; and (c) they consent to both the
          disclosure and the use/processing of their information in accordance
          with this Policy. This Policy applies to all the current and former
          visitors, Users and others who access this Platform.
        </p>
        <p>
          By visiting our Platform or using our services in any way, you
          represent that you are at least the age of majority in your state or
          province of residence or have given Us your consent to allow any of
          your minor dependents to use the Platform.
        </p>
        <p>
          If you are unwilling or unable to be legally bound by this Policy,
          please do not use the Platform.
        </p>
        <p>
          This Policy shall be deemed to be incorporated into the terms of use
          of the Platform (the “
          <span className="font-bold">
            <a
              href="https://xcellify.com/TermsOfUse"
              className="text-blue-600 underline"
            >
              Terms of Use
            </a>
          </span>
          ”) and shall be read in addition to the Terms of Use. In the event of
          any conflict between this Policy and the Terms of Use, the
          interpretation placed by the Company shall be final and binding on
          you.
        </p>
        <h2 className="text-2xl font-semibold mt-6">1. SCOPE OF THIS POLICY</h2>
        <div className="flex">
          <strong className="mr-2">1.1.</strong>
          <p className="flex-1">
            By accessing or using the Platform or otherwise giving Us your
            information, you undertake that you have the capacity to enter into
            a legally binding contract vide this Policy, which constitutes a
            legally binding document between you and the Company under the
            applicable laws including the Indian Contract Act, 1872. The Company
            will collect and process your personal data carefully, only for the
            purposes described in this Policy and only to the extent necessary
            as defined herein and within the scope of the applicable legal
            regulations. This Policy seeks to ensure that any personal
            information handled by the Company is managed in a way that is
            ethical, compliant and adheres to best industry practices.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">1.2.</strong>
          <p className="flex-1">
            Please read the terms and conditions of this Policy carefully,
            before accessing or using this Platform. By accessing or using the
            Platform including its informational services provided via the
            Platform, you agree to the terms of this Policy. If you are
            accepting this Policy on behalf of another person or company or
            other legal entity, you represent and warrant that you have full
            authority to bind such person, company or legal entity to these
            terms.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">1.3.</strong>
          <p className="flex-1">
            This Policy describes the types of information the Company collects,
            why and how the Company uses the information, with whom the Company
            shares it, and the choices you can make about the Company’s use of
            the information. This Policy also describes the measures the Company
            takes to protect the security of the information and how you can
            contact the Company about its privacy practices.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">1.4.</strong>
          <p className="flex-1">
            This Policy describes the Company’s current data protection policies
            and practices and may be amended/updated from time to time. Any
            changes to this Policy will become effective upon posting of the
            revised Policy on the Platform and/or upon notification to you. It
            is recommended that you regularly check this Policy to apprise
            yourself of any updates. Your continued use of Platform or provision
            of data or information thereafter will imply your acceptance of such
            updates to this Policy.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">
          2. TYPES OF INFORMATION COLLECTED BY THE COMPANY
        </h2>
        <p>
          We collect various types of information to provide, enhance, and
          secure our services. The information we collect depends on how you
          interact with the Platform, whether as a visitor, registered{' '}
        </p>
        <div className="flex">
          <strong className="mr-2">2.1.</strong>
          <p className="flex-1">
            <span className="font-bold">Personal Information:</span> When you
            create an account as a User, the Company collects information that
            may be used to identify an individual, including, but not limited
            to, the first and last names, address, state, ZIP/Postal code, city,
            profile picture, telephone number, mobile number, age, gender,
            photograph, language, e-mail address, occupation and income level of
            the Parents, parent’s relationship with the minor, government-issued
            identification for verification and payment processing, or any other
            information which you may submit on and through the Platform.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">2.2.</strong>
          <p className="flex-1">
            <span className="font-bold">Student-Specific Information:</span> If
            you are a Student, in addition to your basic account details, we may
            collect the following information to personalize your experience and
            connect you with appropriate Partner: (i) subject preferences and
            learning goals; (ii) grade level or academic background; (iii)
            educational institutions; and (iv) such other information Student
            voluntarily may provide for the use/access of the Platform.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">2.3.</strong>
          <p className="flex-1">
            <span className="font-bold">Business Information: </span> Business
            Information means any information that may be used to identify an
            individual’s business, professional practice including but not
            limited to the name and address of the entity, areas of expertise,
            date of incorporation, credentials of the legal entity (if any)
            including statutory & registration details, e-mail address of the
            entity, contact information of the registered office, financial
            information including bank account details, professional
            certificates, qualifications, any certificates or licenses or
            membership of professional bodies or government accredited bodies,
            practice skills, working hours and days (availability schedule),
            testimonials or reviews provided by Students & other Users, links to
            professional profiles, samples or recorded sessions or testimonials
            of earlier experience in providing those goods or services, years of
            professional experience, teaching/counselling/mentoring methods or
            curriculum preferences, and such other information that you may
            voluntarily provide or required by the Company.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">2.4.</strong>
          <p className="flex-1">
            <span className="font-bold">Payment Information: </span> If you are
            using any payment facility or undertaking any payment transaction on
            the Platform, we may collect your payment information, such as bank
            account details, debit card, credit card details or other payment
            methods, transaction history, including amounts paid and services
            received. All payment data is processed by third-party payment
            processors in compliance with applicable regulations.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">2.5.</strong>
          <p className="flex-1">
            <span className="font-bold">Non-Personal Information: </span> The
            Company may collect Non-personal information that does not
            specifically identify an individual or business, but includes
            information from you, such as your browser type, the URL of the
            previous websites you visited, your internet service provider (ISP),
            operating system & version and your internet protocol (IP) address,
            device location, information about your mobile device including
            hardware model, preferred language, unique device identifier,
            information you provide us when you contact us for help; information
            you enter into our system when using the Platform. The Company may
            gather any non-personal information regarding how many people visit
            the Platform, the pages you visit, how long you visited our
            Platform, the date and time you used the Platform. The Company may
            also collect Non-Personal Information that you voluntarily provide,
            such as information included in response to a questionnaire or a
            survey conducted by the Company.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">2.6.</strong>
          <p className="flex-1">
            <span className="font-bold">Usage Information: </span> Usage
            Information includes without limitation all data and information
            collected automatically through the Platform (or through the third
            party analytics service providers), by use and access of the
            Platform in the nature of system administrative data, statistical
            and demographical data, and operational information and data
            generated by or characterizing use of the Platform including without
            limitation, Non-Personal Information, cookies, your search queries,
            comments, search results selected, number of clicks, pages viewed
            and the order of those pages, error logs, Platform traffic, time
            spent on the Platform, number of visits to the Platform and other
            similar information and behaviour indicating the mode and manner of
            use of the Platform.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">2.7.</strong>
          <p className="flex-1">
            <span className="font-bold">Communications:</span> Any messages,
            emails, or other communications you send to us through the Platform
            (e.g., customer service inquiries, feedback, questions and views
            expressed in the discussion forum or lesson-related questions) may
            be collected to respond to you or improve our services. This may
            include email addresses, phone numbers, the content of your messages
            and any attachments, such as files, images.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">2.8.</strong>
          <p className="flex-1">
            All information collected during the course of usage of the Platform
            including Personal Information, Student-Specific Information,
            Business Information, Payment Information, Non-Personal Information,
            Usage Information, and Communication, shall hereinafter be referred
            to as “Information”. The Company limits the collection of
            Information which is necessary for its intended purpose.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">3. CONSENT</h2>
        <div className="flex">
          <strong className="mr-2">3.1.</strong>
          <p className="flex-1">
            By accepting the terms of this Policy, you expressly consent to the
            Company’s use, access, processing and disclosure of your Information
            in accordance with the terms of this Policy and forms a valid and
            binding agreement between you and the Platform/Company for
            Information processing as per the terms of this Policy (as per
            Section 6 (1) of the Digital Personal Data Protection Act, 2023).
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">3.2.</strong>
          <p className="flex-1">
            In case you wish to avail of any or all of the services provided on
            the Platform, the Company shall provide a method for sign-up and
            login, which may include username and password, mobile number or
            email ID or login through your social media account or any other
            mechanism as may be available on the Platform (“Login Credentials”)
            as set out in the Terms of Use. You may be required to fill in the
            Information on the Platform including full name, email address,
            mobile number, age, subjects you want to learn or teach, products
            and services you seek to avail and you will be required to create a
            login ID, password, pass key and/or any other information as may be
            required to set up your account on the Platform. You hereby
            explicitly agree that your use and access of the Login Credentials
            shall be governed by the Terms of Use read with the terms of this
            Policy and any other agreement that you may enter into with the
            Company. You should not share your Login Credentials, one-time
            password or other security information for your account with anyone.
            If we receive instructions using your Login Credentials, we will
            consider that you have authorized the instructions.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">3.3.</strong>
          <p className="flex-1">
            With regard to the minors, under the age of 18 (Eighteen), they may
            only use the Platform with the express prior consent of their parent
            or legal guardian. A Student under the age of 18 (Eighteen) (“Child
            User”) may only access and use the Platform as a “sub-user” under
            the main account created by their parent or legal guardian. A Child
            User shall not create their own independent account. Before allowing
            the child to login and collecting any additional personal
            information, we will notify the parent or legal guardian via email,
            informing them of the Child User’s request to create an account and
            providing a link to this Privacy Policy and asking the parent or
            legal guardian to accept or reject the Privacy policy and Terms of
            Use, create their Login Credentials and provide consent on behalf of
            the Child as a prerequisite to allow login access to the Child User.
            Further, we will use the parent or legal guardian’s email address to
            inform them of any updates to our Privacy Policy. Parents or legal
            guardians may review, modify, or delete their child’s Personal
            Information at any time by contacting us at
            <a
              href="mailto:customercare@xcellify.com"
              className="underline text-blue-600 hover:text-blue-800"
            >
              customercare@xcellify.com
            </a>
            . The Platform is designed for use by people of any age including
            children under 18 years of age. We do not knowingly collect
            information from children without legal guardian/parental consent,
            in compliance with the Information Technology Act, 2000 and rules
            made thereunder and the Digital Personal Data Protection Act, 2023.
            If we become aware that a Child User has provided us with Personal
            Information without their legal guardian/parent’s consent, we will
            take immediate steps to delete that information.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">3.4.</strong>
          <p className="flex-1">
            If you are a parent or guardian and believe we have collected
            Personal Information from your child in violation of legal
            requirements, please contact us immediately by writing to us at{' '}
            <a
              href="mailto:customercare@xcellify.com"
              className="underline text-blue-600 hover:text-blue-800"
            >
              customercare@xcellify.com
            </a>
            . Should we discover that Personal Information has been collected
            from a Child User without proper legal guardian’s consent as
            required by law, we will take appropriate steps to delete the
            information in accordance with legal obligations.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">3.5.</strong>
          <p className="flex-1">
            You hereby confirm that the information and documents provided by
            you are correct. In the event of any discrepancy found later, you
            will be solely responsible for the legal, statutory and business
            consequences. Moreover, the Company shall be entitled to delete your
            personal account.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">3.6.</strong>
          <p className="flex-1">
            The information in the relevant parts of this notice applies to all
            Users including children as well as adults. If your child faces any
            form of abuse or harassment while availing our services, you must
            write to us at{' '}
            <a
              href="mailto:customercare@xcellify.com"
              className="underline text-blue-600 hover:text-blue-800"
            >
              customercare@xcellify.com
            </a>
            , so that necessary actions may be taken.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">
          4. COLLECTION OF INFORMATION{' '}
        </h2>
        <div className="flex">
          <strong className="mr-2">4.1.</strong>
          <p className="flex-1">
            The Company may collect Information from you when you carry out any
            engagement or transaction on the Platform including but not limited
            to: <br />
            (a)create a profile or account on the Platform; <br />
            (b) engage with services offered by the Platform; <br />{' '}
            (c)voluntarily participate in campaigns or contests conducted by the
            Company on the Platform, or when you respond to surveys, polls, or
            questionnaires published by the Company; <br /> (d) contact us
            through the Platform, whether for support, inquiries, or other
            purposes; <br />
            (e)voluntarily complete a customer survey or provide feedback on any
            of our message boards or via e-mail in relation to the information
            provided on the Platform; <br /> (f) make payments for any services
            available on the Platform; <br /> (g) participate in career
            assessment test and or talk to any of Career Counsellors/Partners on
            the Platform; and <br />
            (h) participate in discussion forum.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">4.2.</strong>
          <p className="flex-1">
            You hereby acknowledge and agree that all Information is provided by
            you to the Company voluntarily and the Information provided by you
            is not subject to any undue influence.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">4.3.</strong>
          <p className="flex-1">
            The Company may use cookies to monitor the Platform usage including,
            without limitation, to provide useful features to simplify your
            experience when you return to the Platform, like remembering your
            Information and to deliver relevant content based on your
            preferences, usage patterns and location.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">4.4.</strong>
          <p className="flex-1">
            The Company may also collect Non-Personal Information or Usage
            Information based on your browsing activity and in relation to your
            use or access to the Platform which may or may not be publicly
            accessible.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">4.5.</strong>
          <p className="flex-1">
            Information collected by the Company from a particular browser or
            device may be used with another computer or device that is linked to
            the browser or device on which such information was collected.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">4.6.</strong>
          <p className="flex-1">
            You may use the Platform without providing the Company any Personal
            Information about yourself. However, you may not be able to access
            certain services of the Platform in case you choose to do so.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">5. USE OF INFORMATION </h2>
        <div className="flex">
          <strong className="mr-2">5.1.</strong>
          <p className="flex-1">
            The Company uses the Information you provide to: (a) fulfil your
            requests for the services offered on the Platform, including by
            facilitating connections with various products or service providers;
            (b) display, set up and maintain your user profile on the Platform;
            (c) respond to your inquiries about its products and services; (d)
            provide you with information about products and services available
            on its Platform, and offer other services that may be of interest to
            you; (e) resolve any issues on the Platform, including addressing
            technical problems; (f) improve the services and content on the
            Platform and enhance your experience navigating through the
            Platform; (g) administer the Platform; (h) understand each user’s
            learning patterns and interactions on the Platform; (i) manage the
            Company’s relationship with you; (j) provide support for the
            services and respond to your requests, questions, and feedback; (k)
            conduct research and analysis to improve our products, services, and
            Platform; (l) use information provided by Students (e.g., subject
            preferences, learning goals, grade level) and other providers of
            products and services to facilitate an effective match between
            Students and Partners, allowing the Platform to recommend
            appropriate Partners or their services/products for Students and
            display Student needs to the Partners.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">5.2.</strong>
          <p className="flex-1">
            The Company may use the Information to monitor your use of the
            Platform and may review and analyse the Information to provide you
            with customized services.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">5.3.</strong>
          <p className="flex-1">
            We may use your Personal Information to comply with applicable laws
            and respond to lawful requests or legal processes, such as
            subpoenas, investigations, or government inquiries. Additionally, we
            may use it to protect the rights, privacy, safety, or property of
            ourselves, or those belonging to you, or others, including by making
            or defending legal claims.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">5.4.</strong>
          <p className="flex-1">
            We may also audit our internal processes to ensure compliance with
            legal, contractual, or policy obligations, enforce the Platform’s
            terms and conditions, and prevent, investigate, and address
            fraudulent, harmful, unauthorized, unethical, or illegal activities
            such as cyberattacks or identity theft.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">5.5.</strong>
          <p className="flex-1">
            In certain instances, we may seek your explicit consent to collect,
            use, or share your Personal Information, particularly when legally
            required.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">5.6.</strong>
          <p className="flex-1">
            We may create aggregated, de-identified, or anonymized data from
            your Personal Information and the information of others. This is
            done by removing details that could identify you. We may use and
            share this anonymized data with third parties for legitimate
            business purposes, such as analyzing and improving the services of
            the Platform and promoting our business.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">5.7.</strong>
          <p className="flex-1">
            The Company may use your Non-Personal Information or Usage
            Information for internal business purposes, such as data analysis,
            research, developing new products and/or features, enhancing and
            improving existing products and intermediary services and
            identifying usage trends.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">5.8.</strong>
          <p className="flex-1">
            Subject to and in accordance with applicable laws, the Company has
            the right to use your Information for the purpose of conducting
            promotional/marketing related activities on the Platform, including
            but not limited to, using your Personal Information for making
            posters/banners as well as contacting you directly or through our
            agents to promote the products and services of the Company.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">5.9.</strong>
          <p className="flex-1">
            When you send an email message or otherwise contact the Company
            through its Platform, the Company may use the Information provided
            by you to respond to your communication. The Company may also
            archive such Information and/or use it for future communications
            with you to inform you regarding updates, newsletters, offers, new
            services and promotions.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">6. INFORMATION SHARING </h2>
        <div className="flex">
          <strong className="mr-2">6.1.</strong>
          <p className="flex-1">
            We are committed to protecting your privacy and only share your
            Personal Information in limited circumstances, as necessary to
            provide our services, comply with legal requirements, or protect our
            interests. This section outlines the situations in which we may
            share your Personal Information and the measures we take to ensure
            your Information is handled responsibly.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">6.2.</strong>
          <p className="flex-1">
            The primary purpose of the Platform is to facilitate connections
            between Students and various Partners as well as creating discussion
            forum. To achieve this, certain Personal Information must be shared
            between Users.
          </p>
        </div>{' '}
        <div className="flex">
          <strong className="mr-2">6.3.</strong>
          <p className="flex-1">
            <span
              className="font-bold
            "
            >
              For Students:
            </span>{' '}
            When you purchase any product or service on our Platform, we may
            share your Personal Information with the relevant Partner, to enable
            the provision of those services outside the Platform. <br /> This
            information may include: <br /> (a) Name; <br /> (b) Contact details
            (e.g., email, phone number); <br />
            (c) Address; <br /> (d) Subject preferences and goals; <br /> (e)
            Availability for classes; <br /> (f) Any additional details
            necessary to facilitate the service.
          </p>
        </div>{' '}
        <div className="flex">
          <strong className="mr-2">6.4.</strong>
          <p className="flex-1">
            The Partner will only have access to Information necessary to
            provide their services and communicate with you directly. You
            control the Information you choose to provide when interacting with
            such Partner.
          </p>
        </div>{' '}
        <div className="flex">
          <strong className="mr-2">6.5.</strong>
          <p className="flex-1">
            <span className="font-bold">For Partner:</span> When you register as
            a Partner on the Platform, we may share certain details about your
            profile with the other Users and publish it on the Platform to help
            them evaluate and select your services. This Information may
            include: <br /> (a) Full name and professional title; <br /> (b)
            Teaching experience, credentials, and subject expertise; <br />
            (c) Pricing for services’ <br />
            (d) Reviews and ratings from other Students; <br /> (e) Profile
            picture (if provided); <br /> (f) Contact details for coordination.
          </p>
        </div>{' '}
        <div className="flex">
          <strong className="mr-2">6.6.</strong>
          <p className="flex-1">
            Other Users will be able to see aforementioned Information when
            searching for or selecting Partner’s products/services or it will be
            generally available on the Platform for Users to see.
          </p>
        </div>{' '}
        <div className="flex">
          <strong className="mr-2">6.7.</strong>
          <p className="flex-1">
            We may share aggregated, anonymized, or de-identified Information
            that cannot reasonably be used to identify you with third parties
            for research, marketing, or analytical purposes. For example, we may
            share aggregated statistics about user demographics, usage patterns,
            or subject preferences with third parties, advertisers, or other
            stakeholders. This type of information does not include any
            personally identifiable information and is used to improve our
            services and understand trends in our user base.
          </p>
        </div>{' '}
        <div className="flex">
          <strong className="mr-2">6.8.</strong>
          <p className="flex-1">
            The Company maintains your Information in electronic form on its
            devices and equipment. The Information is made accessible to
            employees, agents and/or third-parties only on a need-to-know basis.
          </p>
        </div>{' '}
        <div className="flex">
          <strong className="mr-2">6.9.</strong>
          <p className="flex-1">
            The Company does not rent, sell, or share Information with third
            parties or with other non- affiliated entities, except with your
            consent.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">7. ADDITIONAL FEATURES</h2>
        <div className="flex">
          <strong className="mr-2">7.1. Career Assessment Test:</strong>
          <br />
        </div>
        <p className="flex-1">
          <strong className="mr-2">7.1.1.</strong>
          We are committed to protecting your privacy and only share your
          Personal Information in limited circumstances, as necessary to provide
          our services, comply with legal requirements, or protect our
          interests. This section outlines the situations in which we may share
          your Personal Information and the measures we take to ensure your
          Information is handled responsibly.
        </p>
        <p className="flex-1">
          <strong className="mr-2">7.1.2.</strong>
          Use of Information: This information is used solely to provide
          tailored career insights and recommendations. Aggregated, anonymized
          data may be used to enhance and refine the assessment tool but will
          not identify any individual.
        </p>
        <p className="flex-1">
          <strong className="mr-2">7.1.3.</strong>
          Data Sharing: Results of the career assessment test are shared only
          with the individual Student and their Parent or legal guardian, as
          well as the Career Counsellor/Partner engaged by Xcellify to guide the
          Student but it is not disclosed to any Partner or other Users unless
          explicitly shared by the Student.
        </p>
        <div className="flex">
          <strong className="mr-2">7.2. Discussion Forum:</strong>
          <br />
        </div>
        <p className="flex-1">
          <strong className="mr-2">7.2.1.</strong>
          Information Collected: When participating in the discussion forum, we
          collect information such as your username, the content of your posts,
          and interactions with other users.
        </p>
        <p className="flex-1">
          <strong className="mr-2">7.2.2.</strong>
          Use of Information: This information is used to facilitate
          discussions, moderate content, and foster a safe community. Posts may
          be visible to all Users, and Users should avoid sharing sensitive
          personal information in the forum.
        </p>
        <p className="flex-1">
          <strong className="mr-2">7.2.3.</strong>
          Data Sharing: Posts in the discussion forum are visible to other Users
          of the Platform. However, Personal Information from your account (such
          as contact details) will not be shared publicly in the forum unless
          you choose to include it in your posts.
        </p>
        <h2 className="text-2xl font-semibold mt-6">
          8. THIRD PARTY SERVICE PROVIDERS
        </h2>
        <div className="flex">
          <strong className="mr-2">8.1.</strong>
          <p className="flex-1">
            The Company may engage third party service providers and/or
            contractors to perform certain support services for the Company,
            including, without limitation, software maintenance services,
            advertising and marketing services, web hosting services, payment
            gateway, telemarketing and such other related services which are
            required by the Company to provide its intermediary services
            efficiently. These third parties may have limited access to
            Information. If they do, this limited access is provided so that
            they may perform these tasks for the Company and they are not
            authorized by the Company to otherwise use or disclose Information,
            except to the extent required by law. The Company does not make any
            representations concerning the privacy practices or policies or
            terms of use of such websites/third parties, nor does it control or
            guarantee the accuracy, integrity, or quality of the information,
            data, text, software, music, sound, photographs, graphics, videos,
            messages or other materials available on and with such
            websites/third parties.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">8.2.</strong>
          <p className="flex-1">
            The Platform may contain links and interactive functionality
            interacting with the websites of third parties or third parties
            including without limitation the payment gateways, advertisements,
            social media websites, Partner’s website. The Company is not
            responsible for and has no liability for the functionality, actions,
            inactions, privacy settings, privacy policies, terms, or content of
            any such websites or third parties. Before enabling any sharing
            functions to communicate with any such websites or otherwise
            visiting any such websites, the Company strongly recommends that you
            review and understand the terms and conditions, privacy policies,
            settings, and information- sharing functions of each such
            third-party websites.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">9. COOKIES</h2>
        <div className="flex">
          <strong className="mr-2">9.1.</strong>
          <p className="flex-1">
            To enhance your experience with the Platform, many of the
            web/application pages use “cookies” and pixel tags and clear gifts
            on certain pages of the Platform. Cookies are text files the Company
            places in your computer’s/mobile’s browser to maintain your log-in
            and session details. Company uses three types of cookies, necessary
            session cookies (including username, email ID, user access
            information) which enable Company to recognise you and makes it
            easier for you to return to the Platform and interact with the
            Company’s services without signing in again, and/or preference
            cookies (including search and browsing history) which are stored for
            the maximum duration permitted by law, and/or statistics cookies
            (including Usage Information such as unique request ID, statistical
            data) which are stored for the maximum duration permitted by law
            (collectively referred to as the “Cookies”).
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">9.2.</strong>
          <p className="flex-1">
            Cookies, by themselves, do not tell the Company your e-mail address
            or other personally identifiable information unless you choose to
            provide this information to the Company by, for example, registering
            on the Platform and/or by availing the services provided on the
            Platform. Cookies are designed to hold a marginal amount of data
            specific to a particular user and Platform and can be accessed
            either by the web server or the user device. However, once you
            choose to furnish the Platform with personally identifiable
            information, this information may be linked to the data stored in
            the Cookies. Company uses Cookies to understand site usage and to
            improve the content and offerings on the Platform. For example,
            Company may use Cookies to personalize your experience on the
            Platform (e.g., to recognize you by name when you return to the
            Platform). Company also may use Cookies to offer you products,
            programs, or services. Cookies may be placed on the Platform by
            third parties as well, the use of which the Company does not
            control. You are free to accept or refuse the use of Cookies via the
            cookie banner that appears when you open/access the Platform.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">9.3.</strong>
          <p className="flex-1">
            Cookies are retained in your browser unless specifically deleted,
            depending on the type of Cookies. If you decline the Cookies, you
            may be unable to use certain features on the Platform and you may be
            required to re-enter your password frequently. By using or accessing
            the Platform and/or the services provided on the Platform, you
            hereby explicitly authorise the Company and give your consent to the
            Company to store, use and access Cookies for the purposes outlined
            in this Policy. Most browsers allow you to control Cookies through
            their settings, which may be adapted to reflect your consent to the
            use of Cookies, and they may also enable you to review and erase
            Cookies.
          </p>
        </div>{' '}
        <div className="flex">
          <strong className="mr-2">9.4.</strong>
          <p className="flex-1">
            You can manage browser Cookies through your browser settings. The
            ‘Help’ feature on most browsers will tell you how to prevent your
            browser from accepting new cookies, how to have the browser notify
            you when you receive Cookies, how to disable Cookies, and when
            Cookies will expire. If you disable all Cookies on your browser,
            neither We nor third parties will transfer Cookies to your browser.
            If you do this, however, you may have to manually adjust some
            preferences every time you visit the Platform and some features and
            services may not work.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">
          10. DISCLOSURE TO ACQUIRERS
        </h2>
        <div className="flex">
          <p className="flex-1">
            The Company may disclose and/or transfer Information to an investor,
            acquirer, assignee or other successor entity in connection with a
            sale, merger, or reorganization of all or substantially all of the
            equity, business or assets of the Company.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">11. YOUR RIGHTS</h2>
        <div className="flex">
          <strong className="mr-2">11.1.</strong>
          <p className="flex-1">
            You have the right to change your mind and withdraw permission, for
            Us to use your Personal Information. Here is what you can do:
          </p>
        </div>
        <p>
          11.1.1. <span className="font-bold">Withdraw your consent:</span> You
          have the right to withdraw your consent given to us for the Personal
          Information at any point, provided such withdrawal of the consent is
          intimated to the Company in writing through an email at
          <a
            href="mailto:customercare@xcellify.com"
            className="underline text-blue-600 hover:text-blue-800"
          >
            customercare@xcellify.com
          </a>{' '}
          requesting the same. However, the Personal Information already shared
          with any Partner or any other third party in terms of this Policy, may
          not be reversed.
        </p>
        <p>
          11.1.2. <span className="font-bold">Opt-out of Communications:</span>{' '}
          You can unsubscribe from marketing emails by following the
          instructions provided in the email or by making a request in your
          profile page. However, please note that opting out of marketing emails
          may not stop service related or other non-marketing communications.
        </p>{' '}
        <p>
          11.1.3. <span className="font-bold">Privacy Settings:</span> Partners
          have the ability to control the visibility of their public profiles on
          the Platform.
        </p>
        <p>
          11.1.4. <span className="font-bold">Delete/Close Account:</span> You
          can remove certain content through your account. If you wish to close
          your account, you may do so by login into your personal account and
          follow the steps specified on the Platform.
        </p>
        <div className="flex">
          <strong className="mr-2">11.2.</strong>
          <p className="flex-1">
            Once you withdraw your consent to share the Personal Information
            collected by the Company, the Company shall have the option not to
            fulfil the purposes for which the said Personal Information was
            sought and the Company may restrict you from using the services on
            the Platform and/or the Platform itself and disable your personal
            account.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">
          12. RECTIFICATION/ CORRECTION/ DELETION OF PERSONAL INFORMATION
        </h2>
        <div className="flex">
          <strong className="mr-2">12.1.</strong>
          <p className="flex-1">
            You shall have a right to access the Personal Information that you
            have provided to the Company through the use of the Platform by
            login to your personal profile.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">12.2</strong>
          <p className="flex-1">
            You shall have the right to review your Personal Information
            submitted by you on the Platform and to modify or delete any
            Personal Information (as the case may be), provided by you directly
            on the Platform. You hereby understand that any such modification or
            deletion may affect your ability to use the Platform. Further, it
            may affect the Company’s ability to provide its intermediary
            services to you.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">12.3.</strong>
          <p className="flex-1">
            The Company reserves the right to verify and authenticate your
            identity and your account Information and/or payment Information in
            order to ensure accurate delivery of services. Access to or
            correction, updating or deletion of your Personal Information may be
            denied or limited by the Company if it would violate another
            person’s rights and/or is not otherwise permitted by applicable law
          </p>
        </div>{' '}
        <div className="flex">
          <strong className="mr-2">12.4.</strong>
          <p className="flex-1">
            If you need to update or correct your Personal Information that the
            Company may have collected to offer you personalized services and
            offers, you may update and correct such details by accessing your
            personal profile by providing supporting documents for such
            rectification of Personal Information. The Company will take all
            reasonable efforts to incorporate the changes within a reasonable
            period of time.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">
          13. TERM OF STORAGE OF PERSONAL INFORMATION
        </h2>
        <div className="flex">
          <strong className="mr-2">13.1.</strong>
          <p className="flex-1">
            The Company will store your Personal Information only as long as
            necessary to provide the Platform and for legitimate business
            purposes, such as maintaining Platform performance, making
            data-driven decisions, complying with legal obligations, and
            resolving disputes.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">13.2</strong>
          <p className="flex-1">
            We will also store your Information for at least the duration
            required or permitted by law or as necessary to fulfil the purpose
            for which it was collected. The retention period will vary based on
            the nature of the Information and your interactions with the
            Company.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">13.3.</strong>
          <p className="flex-1">
            You agree that you will not submit any false Information or any
            illegal or damaging content to the Platform. The Company reserves
            the right to terminate access to or the ability to interact with the
            Platform in response to any concerns the Company may have about
            false, illegal, or damaging content submitted by you, or for any
            other reason, in its sole discretion. Moreover, you will be solely
            responsible for any consequences including action by law enforcement
            authorities or legal action by any affected parties without any
            liability to Xcellify.
          </p>
        </div>{' '}
        <h2 className="text-2xl font-semibold mt-6">
          14. PROTECTION OF INFORMATION
        </h2>
        <div className="flex">
          <strong className="mr-2">14.1.</strong>
          <p className="flex-1">
            The Company has taken adequate measures to protect the security of
            Information and to ensure that your choices for its intended use are
            honoured. The Company takes robust precautions to protect your data
            from loss, misuse, unauthorized access or disclosure, alteration, or
            destruction.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">14.2</strong>
          <p className="flex-1">
            The Company considers the confidentiality and security of your
            information to be of utmost importance. It, therefore, uses industry
            standards, and physical, technical and administrative security
            measures to keep Information confidential and secure and the Company
            will not share your Information with third parties, except as
            otherwise provided in this Policy. Please be advised that, however,
            while the Company strives to protect Information and privacy, the
            Company cannot guarantee or warranty its absolute security when
            Information is transmitted over the internet into the Platform. The
            Company will annually evaluate this necessity considering your
            privacy and our relationship while keeping the applicable
            legislation in mind. Non-Personal Information will be retained
            indefinitely.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">14.3.</strong>
          <p className="flex-1">
            For any loss or theft of Information, due to unauthorized access to
            your device through which you use the Platform or other reasons
            solely attributable to you, the Company shall not be held liable or
            responsible under any circumstance whatsoever. Further, the Company
            shall not be responsible for any breach of security or for any
            actions of any third parties/Partners or events that are beyond the
            Company’s reasonable control including but not limited to acts of
            government, computer hacking, unauthorised access to computer data
            and storage device, computer crashes, breach of security and
            encryption, poor quality of internet service or telephone service of
            the user, etc.
          </p>
        </div>{' '}
        <h2 className="text-2xl font-semibold mt-6">
          15. LIMITATION OF LIABILITY
        </h2>
        <div className="flex">
          <strong className="mr-2">15.1.</strong>
          <p className="flex-1">
            The Company shall not be liable to you for any wrong career choice,
            performance in any competition or examination, quality of any
            product or service, non receipt of anticipated results in any
            activity or event or examination or program or course, loss of
            profit, anticipated savings, goodwill, reputation or business
            opportunities or any type of direct or indirect, incidental,
            economic, compensatory, punitive, exemplary or consequential losses
            arising out of performance or non-performance of its obligations
            under this Policy.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">15.2</strong>
          <p className="flex-1">
            The Company is not responsible for any actions or inactions of any
            third parties, that receive your Information.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">15.3.</strong>
          <p className="flex-1">
            Notwithstanding anything contained in this Policy or elsewhere, the
            Company shall not be held responsible for any loss, damage or misuse
            of your Information, if such loss, damage or misuse is attributable
            to a Force Majeure Event and/or any third party. The term “Force
            Majeure Event” shall mean any event that is beyond the reasonable
            control of the Company and shall include, without limitation,
            sabotage, fire, flood, explosion, acts of God, civil commotion,
            strikes, lockouts or industrial action of any kind, riots,
            insurrection, war, acts of government, computer hacking, civil
            disturbances, unauthorised access to computer data and storage
            device, computer crashes, breach of security and encryption,
            epidemic, pandemic or national/state lockdown due to any reason and
            any other similar events not within the control of the Company and
            which the Company is not able to overcome.
          </p>
        </div>{' '}
        <h2 className="text-2xl font-semibold mt-6">16. DISCLAIMER</h2>
        <div className="flex">
          <strong className="mr-2">16.1.</strong>
          <p className="flex-1">
            WHILE WE AIM TO PROVIDE BEST SERVICES WITH REASONABLE SECURITY AND
            SAFETY PROTOCOLS, THE PLATFORM IS OFFERED ON AN “AS-IS” AND “AS-
            AVAILABLE” BASIS AND WE DO NOT GUARANTEE THE ACCURACY, OR THE
            AVAILABILITY OF THE PLATFORM AND THE USE OF THE PLATFORM IS ENTIRELY
            AT THE USER’S OWN RISK. THE PLATFORM FUNCTIONS SOLELY AS AN
            INTERMEDIARY FACILITATING THIS PROCESS. THE PLATFORM/COMPANY WILL
            NOT BE LIABLE FOR ANY DISPUTES, CLAIMS, OR DAMAGES ARISING BETWEEN
            THE USERS IN RELATION TO THE ACTS, OMISSIONS, MISCONDUCT OR ANY
            REASON WHATSOEVER INCLUDING PARTNER’S PRODUCTS OR SERVICES.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">16.2</strong>
          <p className="flex-1">
            USERS SHALL COMPLY WITH ALL APPLICABLE LAWS, INCLUDING DATA
            PROTECTION LAWS, WHILE USING THE PLATFORM. ANY MISUSE OF THE
            PLATFORM IN VIOLATION OF SUCH LAWS IS THE SOLE RESPONSIBILITY OF THE
            USER. AS A CONDITION TO YOUR USE OF THE PLATFORM, YOU AGREE THAT YOU
            WILL NOT TAKE ANY ACTION INTENDED TO: (I) ACCESS DATA THAT IS NOT
            INTENDED FOR YOU; (II) INVADE THE PRIVACY OF, OBTAIN THE IDENTITY
            OF, OR OBTAIN ANY PERSONAL INFORMATION ABOUT ANY OTHER USER OF THIS
            PLATFORM; (III) PROBE, SCAN OR TEST THE VULNERABILITY OF THE
            PLATFORM OR BREACH SECURITY OR AUTHENTICATION MEASURES WITHOUT
            PROPER AUTHORIZATION; (IV) ATTEMPT TO INTERFERE WITH SERVICE TO ANY
            USER, HOST OR NETWORK OR OTHERWISE ATTEMPT TO DISRUPT OUR
            BUSINESS,INCLUDING, WITHOUT LIMITATION, VIA MEANS OF SUBMITTING A
            VIRUS TO THE PLATFORM, OVERLOADING, “FLOODING,” “SPAMMING,” “MAIL
            BOMBING” , “PHISHING”, “SPOOFING”, “IDENTITY THEFT”, “HACKING”,
            “CYBERSTALKING”, “MALVERTISING” OR “CRASHING” THE PLATFORM; OR (V)
            SEND UNSOLICITED MAIL, INCLUDING PROMOTIONS AND/OR ADVERTISING OF
            PRODUCTS AND SERVICES.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">16.3.</strong>
          <p className="flex-1">
            THE COMPANY DISCLAIMS ANY LIABILITY FOR ANY EVENT CAUSED BY THE
            ACTIONS/INACTIONS OF THE USER OR ANY THIRD PARTY. IN ORDER TO
            PROTECT YOUR ACCOUNT FROM ANY HARM, LOSS AND MISUSE OF YOUR
            INFORMATION, REASONABLE PHYSICAL, ADMINISTRATIVE, TECHNICAL AND
            ELECTRONIC SECURITY MEASURES HAVE BEEN IMPLEMENTED. HOWEVER, THESE
            MAY BE VARIED ACCORDING TO THE SENSITIVITY OF SUCH INFORMATION.
            FURTHERMORE, THE COMPANY DOES NOT GUARANTEE THAT THESE MEASURES ARE
            PERFECT OR IMPENETRABLE TO ANY CYBER / VIRUS ATTACK OR SECURITY
            BREACH AND INFORMATION WILL REMAIN SECURE.
          </p>
        </div>{' '}
        <h2 className="text-2xl font-semibold mt-6">17. GOVERNING LAW</h2>
        <div className="flex">
          <strong className="mr-2">17.1.</strong>
          <p className="flex-1">
            This Privacy Policy and any disputes arising out of or related to it
            shall be governed by and construed in accordance with the laws of
            India, without regard to its conflict of laws principles.
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">17.2</strong>
          <p className="flex-1">
            Any legal action or proceeding arising under this Privacy Policy
            shall be brought exclusively in the courts located in Bengaluru,
            Karnataka, India and you consent to the jurisdiction of such courts.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">
          18. GRIEVANCE REDRESSAL MECHANISM
        </h2>
        <div className="flex">
          <strong className="mr-2">18.1.</strong>
          <p className="flex-1">
            In accordance with the Information Technology Act, 2000 and Rules
            made thereunder along with Section 13 of the Digital Personal Data
            Protection Act, 2023, you have the right to readily available means
            of grievance redressal in relation to your Information collected by
            the Platform. Therefore, the Platform/Company respects your rights
            and is hereby furnishing the name and contact details of the
            Grievance Officer, as provided below:
            <br />
            <br /> Name: Pradipta Sahoo <br />
            <br /> Cell: 9019033343 <br /> <br />
            E-mail: pradipta@xcellify.com
          </p>
        </div>
        <div className="flex">
          <strong className="mr-2">18.2</strong>
          <p className="flex-1">
            In case your grievance was not handled in compliance of the
            applicable laws by the Company, you have the right to file
            appropriate complaints (as per the prescribed rules) with the Data
            Protection Board of India under the provisions of the Digital
            Personal Data Protection Act, 2023.
          </p>
        </div>
        <h2 className="text-2xl font-semibold mt-6">19. HOW TO CONTACT US</h2>
        <div className="flex">
          <strong className="mr-2">18.1.</strong>
          <p className="flex-1 mb-10">
            If you have any questions or concerns about this Policy, you may
            contact the Company at{' '}
            <a
              href="mailto:customercare@xcellify.com"
              className="underline text-blue-600 hover:text-blue-800"
            >
              customercare@xcellify.com
            </a>
            .
          </p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicyScreen;
